### ISSUE TITLE
Receiving errors when trying to index test_pcaps

### ISSUE THREAD

**Issue by Betsworth22** [vichargrave/espcap#1]
Traceback (most recent call last):
  File "/home/testadmin/espcap/src/capture/file_capture.py", line 65, in capture
    helpers.bulk(es, index_packets(capture, pcap_file, file_date_utc), chunk_size=chunk, raise_on_error=True)
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 183, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File "/usr/local/lib/python2.7/dist-packages/elasticsearch/helpers/__init__.py", line 156, in streaming_bulk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors)

**Comment by Betsworth22** [comment]
I also get around 100 attempts that output this data. I'm guessing because that it is the default chunk size. 

BulkIndexError: ('100 document(s) failed to index.', [{u'create': {u'status': 400, u'_type': u'pcap_file', u'_id': u'AU_2hhT-xCW93Cn9bsvu', u'error': {u'reason': u"Field name [dns.count.add_rr] cannot contain '.'", u'type': u'mapper_parsing_exception'}, u'_index': u'packets-2015-08-14'}}, {u'create': {u'status': 400, u'_type': u'pcap_file', u'_id': u'AU_2hhT-xCW93Cn9bsvv', u'error': {u'reason': u"Field name [dns.count.add_rr] cannot contain '.'", u'type': u'mapper_parsing_exception'}, u'_index': u'packets-2015-08-14'}}

**Comment by Betsworth22** [comment]
I went ahead and tried the recommended anaconda edition of python also just to see if the default version of python included with Ubuntu was not sufficient. Same error. 

vTraceback (most recent call last):
  File "/home/optivadmin/espcap/src/capture/file_capture.py", line 65, in captur                                                                                                             e
    helpers.bulk(es, index_packets(capture, pcap_file, file_date_utc), chunk_siz                                                                                                             e=chunk, raise_on_error=True)
  File "/home/optivadmin/anaconda/lib/python2.7/site-packages/elasticsearch/help                                                                                                             ers/__init__.py", line 183, in bulk
    for ok, item in streaming_bulk(client, actions, **kwargs):
  File "/home/optivadmin/anaconda/lib/python2.7/site-packages/elasticsearch/help                                                                                                             ers/__init__.py", line 156, in streaming_bulk
    raise BulkIndexError('%i document(s) failed to index.' % len(errors), errors

**Comment by vichargrave** [comment]
I'm going to ask what may be obvious questions, but I just want to make sure we've covered the easy possibilities first.

1. Did you install all the required packages: wireshark/tshark, pyshark and Elasticsearch library?
2. Did you set the path of tshark in your pyshark config file?
3. Is Elasticsearch running at the IP address and port you specified on the command line with the 
--node option?

**Comment by Betsworth22** [comment]
Hi Vic,

Yes I installed all the required packages. PyShark, Elasticsearch Library and Wireshark.
I did put the tshark path in the pyshark config file
Elasticsearch is running at the ip:port and is accessible by other applications talking to it directly like this one.

**Comment by Betsworth22** [comment]
Any issues with the new version of Elasticsearch. I believe that I am on the 1.2.0 beta1

**Comment by Betsworth22** [comment]
I will continue to work the problem today. On another note, Any way to extract payloads with ESPcap and index those in elasticsearch?

**Comment by vichargrave** [comment]
First. let me try espcap out on a Ubuntu system.  Perhaps there is a bug for that platform I need to fix.  

As for the payload extraction, that can be a little dicey since each protocol has different tshark layers in which the payloads reside.  Basically anything that is marked as "application" or has an envelope field set to the application level protocol, e.g. "envelope": "http" (if your app level protocol is http), will be the payload.  But you raise a good point, perhaps there should be a way to store the whole application payload.  I'll give it some thought.

Anyhow I'll get back to you with the results of my Ubuntu experiment.  Thanks for your patience.

**Comment by vichargrave** [comment]
I set up all the espcap components on a Ubuntu virtual machine. I just tried the file capture but it worked fine.  Perhaps there is an issue with Elasticsearch 2.0.0-beta1.  I'll give that Elasticsearch version a try next.

**Comment by vichargrave** [comment]
OK so I tried Elasticsearch 2.0.0-beta2.  It turns out that could not update the index containing packet data that I had in Elasticsearch 1.7.2.  One of the reasons is that field names cannot contain periods as some of the tshark field names do.  I think this may have something to do with your problem. 

My suggestion is to use Elasticsearch 1.7.2 until I fix this issue.

**Comment by Betsworth22** [comment]
Thanks Vic. I will give it a try.

**Comment by vichargrave** [comment]
Another update.  I figured out a clean way to add the fields without the periods in the name.  Give me another day and I'll have a version that works with Elasticsearch 2.x and previous versions.

**Comment by vichargrave** [comment]
I've checked in the code that changes the field names to an Elasticsearch 2.x compatible format.  However, I'm getting the - 'NoneType' object has no attribute 'add_reader' - error more consistently when reading packets from a pcap file.  This problem rarely happens with live capture.

Also I'm tempted to change the JSON field format to indicate the protocol on the field name.  For example instead of "layers.network.src" for IP source address it may make more sense to represent it like this "layers.ip.src".  If you agree let me know.

**Comment by vichargrave** [comment]
OK I changed the layer names to the protocol layer name I get from Pyshark. This definitely makes more sense.  I still don't know what to do about the 'NoneType' object has no attribute 'add_reader'  error.  I'll keep you posted.

**Comment by vichargrave** [comment]
Note I have set requirements for the pyshark and trollius versions that get rid of the 'NoneType' error.  So I'm going to close this issue.
