### ISSUE TITLE
count=0 never saves any packets

### ISSUE THREAD

**Issue by sipvoip** [vichargrave/espcap#2]
If I run:

python3 espcap.py --node=elasticsearch.vocinity.net:9200 --nic=eth1 --count=100 --bpf="udp port 5060"

Things work fine, but if I use --count=0 so I can leave it up, it never saves anything to elastic search.

**Comment by vichargrave** [comment]
OK I'll take a look at it.   Thanks for letting me know.

**Comment by vichargrave** [comment]
I think your issue is the chunk size.  This is the number of packets that the Elasticsearch Python bulk API will cache before sending to the Elasticsearch cluster.  The default is 1000, so if you have a restrictive packet filter (like tcp port 443) on a home network, it may take awhile to get to 1000 packets.  Set your chunk size to 100.  At any rate, espcap seems to be working fine.  I did discover that I failed to put the pyyaml dependency in the requirements files, so I added that.  Thanks for using espcap.
